version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: ${DB_NAME:?DB_NAME required}
      POSTGRES_PASSWORD: ${DB_PASSWORD:?DB_PASSWORD required}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    container_name: dvelupmint-db

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: ${DB_NAME:?DB_NAME required}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD:?DB_PASSWORD required}
      JWT_SECRET: ${JWT_SECRET:?JWT_SECRET required}
      SPRING_APPLICATION_NAME: demo
    depends_on:
      - postgres
    volumes:
      - maven_repo:/root/.m2
    container_name: backend

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    container_name: frontend

volumes:
  postgres_data:
  maven_repo:
